java.d: prevent integer overflow when updateEvery > 2s
simonnagl/netdata pull request #7
Opened 2018-04-30 10:32 UTC by illes

2018-04-30 19:10 UTC, simartn requested changes
Thank you for this commit. Can you also provide a test case which would fail with the previous implementation to prevent rolling it back once again?

2018-04-30 19:10 UTC, simonnagl commented on java.d/src/main/java/org/firehol/netdata/utils/AlignToTimeIntervalService.java
> +			throw new IllegalArgumentException("interval cannot be negative: " + interval);
Error message does not fit edge case 0:
interval cannot be negative: 0

2018-05-01 08:36 UTC, illes commented
Gotcha, rbased on the test-case 5d182bb

2018-05-01 16:12 UTC, simartn approved these changes

2018-05-01 16:12 UTC, merged